### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by trmdi** [tsujan/BreezeEnhanced#1]
Some guys would love a transparent blur titlebar for Konsole, like what SierraBreeze and BreezeBlurred can do. Will you add such an option ?

![breezeblurred](https://github.com/alex47/BreezeBlurred/raw/master/BreezeBlur_screenshot5.PNG)
![sierrabreeze](https://github.com/ishovkun/SierraBreeze/raw/master/Screenshot.png)

**Comment by tsujan** [comment]
With BreezeEnhanced, there's no need to that ;) If you want all title-bars to be opaque but Konsole's title-bar to be translucent (and blurred), please try this:

(1) Add this overrdie:

![1](https://user-images.githubusercontent.com/981076/46493768-0f88d580-c81e-11e8-9da9-7d024cd15682.png)

(2) then add this one *to the top of it*:

![2](https://user-images.githubusercontent.com/981076/46493799-262f2c80-c81e-11e8-9c65-24c2512cfb66.png)

BTW, today, I'll add an option to remove macOS buttons, although they will be the default. The reason is that macOS buttons may not be good with all themes.

**Comment by tsujan** [comment]
Oh, don't forget to make the title-bar translucent in the above experiment!

**Comment by trmdi** [comment]
Btw, I think you can make this decoration much better by supporting theming. Something like aurorae engine of kde, but it seems to be buggy and lacks maintenance.

**Comment by trmdi** [comment]
Yes, I mean the buttons.
I'm not sitting in front of my computer so I can't test it now. I will tell you the result tomorrow.

**Comment by tsujan** [comment]
> Yes, I mean the buttons.

With Breeze, buttons are drawn in the code. So, there aren't many options.

> I will tell you the result tomorrow.

Take your time! Since it worked here, it should also work there :)

**Comment by trmdi** [comment]
Yep, I can do it.

But how can I apply that effect **only** to the main window of Konsole? 
If I do like you told me, it also applies to other windows/dialogs... of Konsole.
Can you make BreezeEnhanced's window-selection like the Kwin's one ? It lacks Window Role, Window type...

![image](https://user-images.githubusercontent.com/11857205/46516496-2c5ff000-c894-11e8-96de-4b5ba9406df3.png)

**Comment by trmdi** [comment]
> With Breeze, buttons are drawn in the code. So, there aren't many options.

What about button color and horizontal space between buttons ?

**Comment by trmdi** [comment]
> Therefore, to bring quality to development, I should do things little by little, program by program.

It should be like that. I just drop my idea here when it appears in my head in case I forget it afterwards. :D

Ah, another thing is, do you think the buttons of inactive windows should be gray? Look at my screenshot above, too many colored circles there. :p

**Comment by kupiqu** [comment]
>>And add other macOS style buttons like Keep above, Keep below...

> I had added them at first but found them like an overkill: the title-bar was filled with colored circles and looked really weird.

Maybe if they all are in the same side, but I find them fine if keep above and show in all desktops appear on the left and the rest on the right, which is what I use. Perhaps these could be made optional, but IMO, if you don't like color buttons there is no reason to use Mac style decorations in the first place.

> do you think the buttons of inactive windows should be gray? Look at my screenshot above, too many colored circles there. An option may be good for everyone :p

Certainly, I find this confusing about the active window (and more overkill color issue than adding colors for keep above and show in all desktops.

But just my 2cts.

Congrats btw for the animation, I really find it very nice

**Comment by tsujan** [comment]
@trmdi 

I reopen this page because it contains ideas to be implemented.

> I just drop my idea here when it appears in my head

And please keep on doing so!

> do you think the buttons of inactive windows should be gray?

I had experimented with that too. There was a problem: the buttons couldn't be distinguished from each other. All people could get used to Red → Close, Green → Maximize, Yellow/Orange → Minimize. But gray buttons might cause confusion to some.

@kupiqu

> ...  if you don't like color buttons there is no reason to use Mac style decorations in the first place.

My decision wasn't final. I might return to this later.

**Comment by tsujan** [comment]
> Look at my screenshot above, too many colored circles there

That's a good point too. Maybe, I should gray out the inactive buttons a little more.

**Comment by trmdi** [comment]
> There was a problem: the buttons couldn't be distinguished from each other. All people could get used to Red → Close, Green → Maximize, Yellow/Orange → Minimize. But gray buttons might cause confusion to some.

Can you make the buttons display the color when the mouse is inside the titlebar region, and gray if not ?

**Comment by tsujan** [comment]
> Can you make the buttons display the color when the mouse is inside the titlebar region, and gray if not ?

For inactive windows? I should see if there is such a property ("cursor inside title-bar")... Will tell you about it.

**Comment by kupiqu** [comment]
>> ... if you don't like color buttons there is no reason to use Mac style decorations in the first place.

> My decision wasn't final. I might return to this later.

Sounds good!

Btw, "you", above, was general, referred to a potential final user, not specifically to you as developer. I should have wroten "if one doesn't like color buttons...". 

Again, that's just my opinion (I guess that's why I'm still using SierraBreeze decoration, but I see a lot of good progress here, congrats).

**Comment by tsujan** [comment]
@kupiqu I try to follow user's opinions AND practicality. The practical side isn't strong in the case of colorized secondary buttons, while it is important with gray inactive buttons. So, in the first case, I can forget about my taste but, in the second case, I should find a middle way :)

**Comment by kupiqu** [comment]
In SierraBreeze, hovering buttons of inactive windows show "x" for close, "-" for minimize, etc. I guess there is a way to instead replace gray by the color (red, yellow/orange, etc) on hovering, if you'd like that option.

**Comment by tsujan** [comment]
> ... I guess there is a way to instead replace gray by the color (red, yellow/orange, etc) on hovering

This seems to be the best compromise. I'll go with it.

**Comment by tsujan** [comment]
I made inactive macOS-like buttons gray with a formula that derives the gray lightness from the background color:

![inactive](https://user-images.githubusercontent.com/981076/46551086-ac617680-c8e3-11e8-94be-a48ee0b4e59d.png)

The next step will be making secondary buttons macOS-like.

**Comment by tsujan** [comment]
macOS secondary buttons are added. All of them are pale blue except for the menu button, which is orange. Their symbols appear on mouse-over, so I don't think there can be any problem, especially because users wouldn't remember various colors. Tests would be appreciated.

The main features mentioned on this page are added. I should think about the other features thoroughly and read some codes. So, I close this.

**Comment by tsujan** [comment]
@trmdi 
As for the space between buttons, I investigated it and found that, unfortunately, it's hard-coded in `kdecoration` -- among several other parameters -- based on font size and other things. So, it can't be changed inside Breeze.

However, IMHO, the defaults of `kdecoration` are good enough.

**Comment by trmdi** [comment]
I just try SierraBreeze, it can do it somehow ???

**Comment by tsujan** [comment]
> I just try SierraBreeze, it can do it somehow ???

Really?! I'll see its code; perhaps I'm missing something.

**Comment by trmdi** [comment]
> > I just try SierraBreeze, it can do it somehow ???
> 
> Really?! I'll see its code; perhaps I'm missing something.

Yep: https://streamable.com/18v4u

**Comment by tsujan** [comment]
Added button spacing in the latest commit. As far as I tested, it didn't have any side effect; even absurd settings, like those in this screenshot, work fine:

![absurd](https://user-images.githubusercontent.com/981076/46569822-6a7a1400-c967-11e8-96c5-c5d8523ec8ce.png)

I should have been braver ;)

**Comment by tsujan** [comment]
By the way, I don't understand why people think this is a macOS title-bar -- I read some comments about that here and there. BreezeEnhanced is what its name says: and enhanced version of Breeze. Yes, its default buttons are macOS-like -- because macOS buttons are elegant -- but that's optional and there's nothing else related to macOS.

**Comment by trmdi** [comment]
Never mind, because they don't like the macOS style. That's all.
But many others like that.
There is not any problem when we learn good things from others.
You're doing everything very well !

**Comment by tsujan** [comment]
> because they don't like the macOS style

Strange! macOS has been always elegant. Their style developers know what they do. Anyhow, tastes differ...

**Comment by trmdi** [comment]
Personally I like both macOS dark and light themes.
Btw, what is the Kvantum theme above? Look quite nice !

**Comment by tsujan** [comment]
> Btw, what is the Kvantum theme above?

Its name is weird: `KvSimplicityTurquoise`. Its roots are in the mac style; it's derived from KvSimplicity, which is derived from OS X Yosemite.

**Comment by tsujan** [comment]
Now that I'm more adventurous, I added a new commit, with which Konsole and other apps can have translucent title-bars more easily.

Just remove the [previous setting](https://github.com/tsujan/BreezeEnhanced/issues/1?_pjax=%23js-repo-pjax-container#issuecomment-427117429) about ".*" and add a value to the new spin-box "Override opacity" in the exception dialog. The following screenshot shows that for QTerminal (a Konsole fork I use under LXQt):

![opacity_override](https://user-images.githubusercontent.com/981076/46571031-b6828400-c97a-11e8-826f-0aa93a61df1e.png)

Of course, you could also create a color scheme and assign it to Konsole in System Settings.

The box "Opaque title bar" is kept for the ease of use. If checked, it disables the opacity override.

I'll think about dialogs later.

**Comment by Luwx** [comment]
There are any plans to update it to 5.14? 

The new shadow they implemented looks gorgeous

![niefgwt](https://user-images.githubusercontent.com/33076480/46574695-d798a400-c97d-11e8-8d10-9afa5f0311e8.png)

**Comment by trmdi** [comment]
@Luwx I tried reducing the Shadow strength to 25% and got the similar effect.

**Comment by tsujan** [comment]
> There are any plans to update it to 5.14?

As soon as a newer versions of KWin comes to Manjaro Testing (soon after it comes into Arch), I'll check the difference between Breeze versions and, if needed, will apply them to BreezeEnhanced.

With Arch based systems, that's fast. Previously, I used Debian sid and should wait for weeks.

**Comment by tsujan** [comment]
Right now, https://download.kde.org/stable/plasma/5.14.0/ can't even be opened ;)

**Comment by trmdi** [comment]
You can use tge Github mirror: https://github.com/KDE/breeze/tree/Plasma/5.14?files=1

**Comment by tsujan** [comment]
> You can use the Github mirror....

I know but I prefer not to deal with unstable versions. The latest version of BreezeEnhanced (mentioned in the file NEWS) should be for the latest stable version of KWin (with a delay of one week or so).

And that's why I could never publish a release -- only the latest git version will be valid.

**Comment by trmdi** [comment]
> I know but I prefer not to deal with unstable versions. 

Oh, I thought they tagged it as 5.14 means that it's the stable release ? Here is the release schedule: https://community.kde.org/Schedules/Plasma_5

**Comment by tsujan** [comment]
> Oh, I thought they tagged it as 5.14 means that it's the stable release

It means it'll be released as a stable version soon. https://download.kde.org/stable/ shows the last stable version.

**Comment by Luwx** [comment]
> @Luwx I tried reducing the Shadow strength to 25% and got the similar effect.

You can get close but what breeze uses right now is not a true box shadow.

Well, 5.14 is pretty much stable now, but I guess it doesn't hurt waiting a few more days  :)

**Comment by tsujan** [comment]
@Luwx Yes, `Breeze::BoxShadowHelper` is new. It'll be straightforward to apply changes to BreezeEnhanced once 5.14 gets stable (and comes to my distro).

**Comment by tsujan** [comment]
@Luwx How did you compile kdecoration 5.14? I added `BoxShadowHelper` to BreezeEnhanced but, for a successful compilation, I had to change `find_package(FFTW REQUIRED)` to `find_package(FFTW3 REQUIRED)` and also comment out a line in `FFTW3Config.cmake` (the second issue is reported here: https://github.com/FFTW/fftw3/issues/130).

**Comment by trmdi** [comment]
I'm not @Luwx but I guess you can use Arch PKGBUILD, e.g. https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/kdecoration

**Comment by tsujan** [comment]
Oh, my big mistake! FFTW is included in cmake modules (which didn't exist before). Will wrestle with it tomorrow.

**Comment by tsujan** [comment]
I couldn't wait until tomorrow (actually, it's tomorrow here). I added `Breeze::BoxShadowHelper` to BreezeEnhanced here and compiled it against KWin 5.13. Shadows look better now but the default intensity is changed from 35% to 100% -- I think KDE users will get confused when 5.14 comes out. Moreover, the new shadow can't be made more intense.

This is the ordinary Breeze 5.13 with a 30% shadow:

![old](https://user-images.githubusercontent.com/981076/46576588-3986f700-c9da-11e8-95e6-6fa115775864.png)

And this is the new BreezeEnhanced (not uploaded) with a 100% shadow:

![new](https://user-images.githubusercontent.com/981076/46576590-558a9880-c9da-11e8-879d-aea504ba6753.png)

The new shadow looks more realistic to me.

The changes could be uploaded so that the new BreezeEnhanced could be compiled with both 5.13 and 5.14 but I prefer to wait until 5.14 gets stable. I'm ready for it, thanks to @Luwx's comment :)

BTW, I found a way of publishing releases. When 5.14 comes out, I'll release 5.13, and the same for other versions....

**Comment by tsujan** [comment]
Oh, the new shadows have a bug when made large: they are a mess with small message-boxes. I think no one has seen it yet. The medium size is OK though.

**Comment by tsujan** [comment]
Plasma 5.14 should be released today and will come to my distro with a short delay. I still think that those box shadows have a problem when they're large but I'm ready to upgrade BreezeEnhanced as soon as Plasma 5.14 comes to Manjaro testing.

**Comment by trmdi** [comment]
/OT
Sorry to bother you, do you have a way to make this be true? https://bugs.kde.org/show_bug.cgi?id=399757
Read Chris Holand's comments. After hours played with C++ and Qt, KDecoration, I can not find one. I see you very good at these, can you give me some insights to continue playing with it. :P

> We can get it to draw a non-animated button. Unfortunately, it's not animated.
![img](https://camo.githubusercontent.com/67c28c4b3a177be7d9cad3b97547c206503329d1/68747470733a2f2f692e696d6775722e636f6d2f586a376154394f2e706e67)
https://gist.github.com/Zren/40f657da96e4d8a29b13d74b74e956c5

What I want is to have animated buttons to be shown with QML.

**Comment by tsujan** [comment]
You're asking that from someone who hates QML and QtQuick ;) I'm serious; IMO, QML is the worse thing happened to Qt.

**Comment by tsujan** [comment]
This is one explanation: https://github.com/lxqt/lxqt/issues/1433 . There others.

**Comment by trmdi** [comment]
Then I want to ask a Qt question.

I'm not saying about the only buttons like in the picture above. This time I created a fully client that has titlebar, window, border... from QML code, and it has the hover effect on close/min/max buttons like a normal window.

But when I try: `connect(m_button, &KDecoration::DecorateButton::onHoveredChanged, [] () { qDebug() << "hmm..."})`
it didn't work as expected when I move the mouse in and out of the buttons.
`m_button` is a object of `BreezeButton` class.

What am I understanding/doing wrong with `connect()` ? Or those buttons are not objects of BreezeButton class?

**Comment by tsujan** [comment]
@trmdi See here:https://github.com/tsujan/BreezeEnhanced/blob/4269128339f581392bdfe66bc72fe8c0a2e82871/breezebutton.cpp#L57

**Comment by trmdi** [comment]
Yes, I mean this. But no qDebug() msg is out ???

**Comment by tsujan** [comment]
BTW, Qt Creator suppresses qDebug() messages in its own output. I don't know whose idea it was but it was a very bad idea.

**Comment by tsujan** [comment]
Maybe a real example could help:

I use a lot of `qDebug()` in Kvantum when doing complex things (and remove them later). `kvantumpreview` and many other apps show the debug messages when I run them in the terminal but, for example, `smplayer` shows nothing.

I think no Qt dev codes without `qDebug()` ;) It's the best tool for finding and fixing bugs.

**Comment by trmdi** [comment]
Awesome, he could bring Kwin buttons onto the Plasma panel. [Link](https://bugs.kde.org/show_bug.cgi?id=399757)
All of you are so brilliant !

I thought something nearly like him, but finally I gave up ! I need learn C++ more, it's so funny. ;)
