### ISSUE TITLE
Add more option for titlebar font

### ISSUE THREAD

**Issue by r0skar** [tsujan/BreezeEnhanced#11]
Is it possible to make the custom title bar font selector a drop-down or a text-input, so that one can define more font weights besides "bold"?

I would like to use a a semi-bold (font-weight: 600) font for the title, but right now I can only choose between normal (400) and bold (700).

**Comment by tsujan** [comment]
Yes, it's possible to add five degrees of boldness (from 1 to 5, with 3 as normal boldness), as I've done in Kvantum -- although many fonts don't support it.

The only problem is backward compatibility; I should first solve that.

**Comment by r0skar** [comment]
Forgot to mention it: IMO its better to use traditional font weights (100-900) instead of 1-5.

**Comment by ripefig** [comment]
is the font setting there for other platforms? KDE settings already allows you to customize the titlebar font.

**Comment by tsujan** [comment]
> is the font setting there for other platforms?

Yes but it controls title-bar font in KDE too -- with it, KDE settings have no control over title-bar font.

> KDE settings already allows you to customize the titlebar font.

Unfortunately, KDE devs didn't want to make it usable outside KDE. That's while kwin can be used outside KDE.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/BreezeEnhanced/commit/1e1d09e5babf59595b7b3ece37e9a5650b701ec4 , following Qt's boldness classification:

![weight](https://user-images.githubusercontent.com/981076/49204983-cd65b580-f3c2-11e8-8bc7-38a0f3ca1e23.png)

Of course, not all fonts support it.
