### ISSUE TITLE
Should gradients be applied to window borders?

### ISSUE THREAD

**Issue by kupiqu** [tsujan/BreezeEnhanced#14]

**Comment by tsujan** [comment]
Yes; otherwise, an ugly shape would result.

**Comment by kupiqu** [comment]
> Yes; otherwise, an ugly shape would result.

Sure, but is it implemented already? Sorry if I'm asking the obvious...

**Comment by tsujan** [comment]
Yes, the gradient is drawn on the right and left parts of the *top* border so that there is no discontinuity. Of course, there should be no gradient for other parts of the border.

This isn't new in BreezeEnhanced; it's inherited from Breeze.

**Comment by kupiqu** [comment]
> Of course, there should be no gradient for other parts of the border.
> 
> This isn't new in BreezeEnhanced; it's inherited from Breeze.

I see, thanks for the clarification!
