### ISSUE TITLE
BreezeEnhanced on Active Window Control ?

### ISSUE THREAD

**Issue by pooh2pooh** [tsujan/BreezeEnhanced#16]
Looks amazing in the window.

But when I make the window full screen and hide the window frame, the control buttons are standard from breeze.

Very cool! Thanks!

**Comment by trmdi** [comment]
You mean buttons on the panel? If so, try `applet-window-buttons` by psifidotos.

**Comment by tsujan** [comment]
@trmdi Thanks for your answer!

@pooh2pooh What's on the panel isn't made by BreezeEnhanced. When a window is made full-screen, there's no title-bar button, unless another app (like Panel or Plasma) adds it.

And happy to know that you like it :)
