### ISSUE TITLE
Cannot Load Library

### ISSUE THREAD

**Issue by Quads9** [tsujan/BreezeEnhanced#18]
After successfully installing the theme following the instructions in the readme (and the ones in BreezeBlurrred readme for openSUSE) I cannot find the BreezeEnhanced theme in my Settings, I can find it using the application menu and it gives the following error: 

```
Cannot load library /usr/lib64/qt5/plugins/org.kde.kdedecoration2/breezeenhanced.so:
(libbreezeenhancedcommon5.so.0: cannot open shared object file: No such file or directory)
```

I am at a loss as to what to do to proceed, system info is the following

- openSUSE Tumbleweed
- KDE Plasma Version: 5.15.4
- KDE Frameworks Version: 5.56.0
- Qt Version: 5.12.2

**Comment by trmdi** [comment]
Why not try the prebuilt package from my repo to save your time?
```bash
sudo zypper ar obs://home:trmdi trmdi
sudo zypper in -r trmdi BreezeEnhanced
```

**Comment by tsujan** [comment]
@trmdi 
Thanks! I was going to call you.

@Quads9 
@trmdi has packages for Tumbleweed. I don't have OpenSUSE and have no clue about the cause of your problem. It's obvious that installation was incomplete. I highly recommend @trmdi's packages (I should add that to README, as I did for Kvantum.).

**Comment by Quads9** [comment]
Oh thanks, as you might figure I didn't know there was such a thing. I'll check it out now.

**Comment by tsujan** [comment]
I keep this open until I add Tumbleweed info to README -- and, perhaps, info on Arch/Manjaro.
