### ISSUE TITLE
Request: Use a unique color for each "macOS-like" button type

### ISSUE THREAD

**Issue by AndydeCleyre** [tsujan/BreezeEnhanced#19]
Ideally, these colors would come from the active KDE/Plasma color scheme, but at the very least they should look different from each other.

![image](https://user-images.githubusercontent.com/1787385/58929195-e1002900-8723-11e9-8e13-de4bd3c76d10.png)

This would make it easier to remember which button is which, since there are no visible symbols without checking each one with a hover.

**Comment by tsujan** [comment]
That's intentional. I don't like a rainbow on the title-bar, so I've chosen a relatively low saturation for the blue and haven't added more colors. 

"on-top", "shade" and "on-all" aren't usually used together — at most, 2 of them are used and even with all 3, there's no practical problem.
