### ISSUE TITLE
Can someone make a PPA?

### ISSUE THREAD

**Issue by krisives** [tsujan/BreezeEnhanced#2]
SierraBreeze has a PPA maintained by @thopiekar - how hard would it be to get a PPA setup for BreezeEnhanced? I haven't used Launchpad in years or packaged up anything in Debian for quite some time and I know the SierraBreeze packages are working great!

Thanks for any help!

**Comment by tsujan** [comment]
I haven't had a Debian-based distro for a long time, using an Arch-based distro.

**Comment by krisives** [comment]
"btw I use arch"

**Comment by thopiekar** [comment]
It wouldn't be hard, but need some time.
Currently I'm on a project and kicking many hours per day. 14.25h yesterday
are an example.

Just remind me next week. Will have enough time then and a jetlag I guess.

Cheers.

>

**Comment by krisives** [comment]
I will also see if I can copy what you did with the SierraBreeze debian packaging. I will ping you in a week if nothing pans out.

**Comment by thopiekar** [comment]
Sure. Good luck!

**Comment by krisives** [comment]
Here is the PPA: https://launchpad.net/~krisives/+archive/ubuntu/breezeenhanced

Here is the recipe that rebuilds it daily based on changes to this GitHub: https://code.launchpad.net/~krisives/+recipe/breezeenhanced-daily

If you wish to add instructions to the `README.md` file they would be:

    sudo add-apt-repository ppa:krisives/breezeenhanced
    sudo apt-get update
    sudo apt install breezeenhanced

Also note I found a way to make Debian packaging happy with the prefixed `V` in the tag names and future packages will automatically use the latest tag from this repository.

**Comment by tsujan** [comment]
> Also note I found a way to make Debian packaging happy with the prefixed V in the tag names

Thank you very much for the nice work! Good to know that Kvantum and BreezeEnhanced will be more accessible to Ubuntu users.

**Comment by tsujan** [comment]
I'd totally forgotten to add @krisives's info to README. @epassaro kindly remnded me of that. Now it's in README.
