### ISSUE TITLE
[Feature request] hide titlebar for gtk apps?

### ISSUE THREAD

**Issue by trmdi** [tsujan/BreezeEnhanced#20]
Is there any way to hide the titlebar only but not the borders?
The `hide titlebar/border` option of Kwin will hide border too, that looks ugly.
If this is possible, we can hide the titlebar for gtk apps e.g. Firefox but still keep their border, this will look better.

**Comment by tsujan** [comment]
I don't think borders can be kept without the title-bar but I'm not sure.

I always remove borders. To me, borderless windows are more elegant. Moreover, KWin borders aren't compatible with most Kvantum themes, especially when their window backgrounds have gradient.

**Comment by trmdi** [comment]
Yeah, I hide the borders too. Actually what I meant is the shadow of windows.

**Comment by tsujan** [comment]
Oh, shadows will be gone when you remove the title-bar? I've never tried that (have never had a reason to remove a title-bar). If so, yes, it'll be ugly.

I'll keep this open until I find the answer but I'm curious: Why do you want to remove the title-bar of any app?

Personally, I tolerate the different look of a few GTK apps I have. Although I could have used Kvantum themes that are clones of GTK themes, frankly, I haven't liked any GTK theme so far ;)

**Comment by trmdi** [comment]
> I'm curious: Why do you want to remove the title-bar of any app?

For example, this firefox window will be more perfect if it has the shadow when we hide the titlebar: https://www.reddit.com/r/kde/comments/8b8y04/firefox_with_csd_in_kde_plasma/

**Comment by tsujan** [comment]
Oh, you want GTK's CSD. That means the decoration is drawn by GTK+, not by KWin, and so, GTK+ is responsible for shadow too.

I don't know how window shadows are drawn by Gnome and why they aren't shown under KDE (or LXQt). However, removal of KWin decoration means removal of everything related to them, including KWin shadows.

In short, decorations can be drawn by both KWin and GTK.

**Comment by tsujan** [comment]
BTW, I think CSD is the only cool idea Gnome3 devs have had (actually, it's borrowed from macOS). It'll be so cool if Qt or KWin could have a counterpart but its implementation would be very complicated if possible.

**Comment by tsujan** [comment]
Wow! https://github.com/johanhelsing/qt-csd-demo

**Comment by trmdi** [comment]
This looks cool too: https://www.reddit.com/r/kde/comments/c7i5zr/kwin_with_gtk_frame_extents_support_sick/

**Comment by tsujan** [comment]
I like these kinds of title-bar. They have a drawback with GTK+: they limit the space for window dragging. Gnome has a bad "solution": it allows dragging from buttons. But the problem won't exist in the Qt world because Qt GUI's could be dragged from any reasonable place -- not buttons, of course ;)

However, there's a downside: For a deeper reason, Wayland doesn't allow dragging from anywhere other than the title-bar. I hope KDE devs will find a workaround for it (and for a few other shortcomings of Wayland).
