### ISSUE TITLE
[Feature Request] Configurable padding between buttons and title.

### ISSUE THREAD

**Issue by Kodehawa** [tsujan/BreezeEnhanced#24]
Title.
I would love to be able to configure the padding (in px) between the buttons and the title (aka, [this](https://i.imgur.com/E81EeEi.png))

I don't know if such feature is possible to implement as a configuration, but it would be amazing to, imo.

**Comment by tsujan** [comment]
I don't know if it's possible in BreezeEnhanced's code but will investigate it later.

I always use centered text:

![centered](https://user-images.githubusercontent.com/981076/67206078-d10c8b80-f41d-11e9-8a08-f97b0363900a.png)

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/BreezeEnhanced/commit/6b1cd4dea014943a061b549f1b77627092a85b0c :

![title_margin](https://user-images.githubusercontent.com/981076/67239011-1602e300-f45b-11e9-8095-6fde146349e1.png)

Please upgrade to the latest git.

Please also note that:

  (1) This is an *extra* margin, which will be added to the current small margin. So, if it's zero (the default), there is still a small margin.

  (2) It is for both left and right sides.

**Comment by Kodehawa** [comment]
Woah I love you.
