### ISSUE TITLE
[Feature Request] Windows-like window buttons as an option.

### ISSUE THREAD

**Issue by Kodehawa** [tsujan/BreezeEnhanced#25]
Since there aren't many Breeze themes out there, I would love if this theme could offer windows-alike window buttons as an option alongside the Breeze-ish and MacOS button themes available now.

Qogir (aurorae) has some pretty nice window buttons that I'd love to see implemented here.
![image](https://user-images.githubusercontent.com/20606963/76966423-b541de80-6904-11ea-8214-7dd5ea6d4258.png)

_Why don't you just use the aurorae theme?_
This theme is way more configurable, and Breeze doesn't have font kerning issues when resizing windows.

**Comment by tsujan** [comment]
> Why don't you just use the aurorae theme?

I know that you asked that question from yourself but the answer is: Any KWin theme other than Breeze and its forks may have serious problems.

As for Windows-like buttons, you could uncheck "macOS-like buttons"; then, only the max button is different from your screenshot and I don't think it's a good idea to add a separate option and code just for it.

**Comment by Kodehawa** [comment]
Was worth a shot. Yeah, aurorae it's quite wonky. The maximize button feels so off to me though :<

Thanks eitherway, I love your theme :D

**Comment by tsujan** [comment]
> The maximize button feels so off to me though

Tastes differ and I try to include all of them but only if that's worth adding extra codes.

**Comment by paulmcauley** [comment]
@Kodehawa , try my Breeze-based theme at https://github.com/paulmcauley/classikstyles
