### ISSUE TITLE
Ubuntu PPA is not in README.md

### ISSUE THREAD

**Issue by epassaro** [tsujan/BreezeEnhanced#26]
Hi! I've noticed someone made a PPA repository https://github.com/tsujan/BreezeEnhanced/issues/2 but this information can't be found on the repository description.

**Comment by tsujan** [comment]
Thanks! I forgot to add it to README. Will keep this open until I do so.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/BreezeEnhanced/commit/27245e7e950f8970d6ad3697a374bbf77d8595dc

Thank you again for the reminder!
