### ISSUE TITLE
[Feature Request] Ability to exclude windows from having shadows

### ISSUE THREAD

**Issue by anesuc** [tsujan/BreezeEnhanced#27]
Hi all,

Is it possible to add the ability to exclude windows from having shadows applied to them? I did try setting window type to dock but that didn't work, at least not with this.

Thanks

**Comment by tsujan** [comment]
I should look into Breeze's code to know if that's possible. Being very busy with other codes, I may not find time to do it soon but I'll tell you.

**Comment by anesuc** [comment]
Ok Thanks for that! Really appreciate it!

**Comment by anesuc** [comment]
@tsujan I found a workaround of applying no title or border in windows rules. So all good now!

**Comment by tsujan** [comment]
@anesuc, yes, in window rules of KDE System Settings → Window Management → Window Rules, you could change many things in specific apps.
