### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by illegalDisease** [tsujan/BreezeEnhanced#3]
This is wonderful to use, now i can finally revoke my configurations to hide the top bar in breeze. However, without a proper package management, it would all be wasted.

Just putting the issue here. I will create it if i have free time.

**Comment by tsujan** [comment]
I can include a `PKGBUILD` in the source but experience has shown me that the Arch community will do it better in AUR.

**Comment by illegalDisease** [comment]
PKGBUILD would be awesome.

**Comment by omni6** [comment]
Here it is:
[breeze-enhaced-git](https://aur.archlinux.org/packages/breeze-enhanced-git/)

**Comment by tsujan** [comment]
@omni6 Thank you very much!

**Comment by omni6** [comment]
Arch updated to kwin 5.14, works without and with recompile .. no issues so far.

**Comment by tsujan** [comment]
@omni6 Yes, but it doesn't have box shadows.

I've made BreezeEnhanced ready for kwin 5.14 and will make a commit as soon as kwin 5.14 comes to Manjaro testing from Arch. I just hope that the bug I see in the box shadow doesn't exist with kwin 5.14.

**Comment by tsujan** [comment]
KWin/Breeze 5.14 came here and I upgraded. Good news: there is no issue in the box shadow :)

I added a commit for 5.14 a few minutes ago. Tests would be appreciated.

Please note that the shadow default settings are changed in Breeze 5.14 and I did the same thing in BreezeEnhanced.

**Comment by omni6** [comment]
@tsujan you noticed?

`[ 41%] Generating breezesettings.h, breezesettings.cpp
/tmp/makepkg/breeze-enhanced-git/src/BreezeEnhanced/config/ui/breezeconfigurationui.ui: Warning: Tab-stop assignment: 'drawTitleBarSeparator' is not a valid widget.
`

**Comment by tsujan** [comment]
@omni6 I was compiled without problem here. Let me download the source and try again...

**Comment by tsujan** [comment]
It's compiled fine but you're right: the warning exists, although it's harmless. The reason is that I've removed that ugly separator but not some codes related to it. Will also remove them soon.

Thanks!

**Comment by tsujan** [comment]
Done!
