### ISSUE TITLE
BreezeEnhanced writes config into Breeze's breezerc file

### ISSUE THREAD

**Issue by paulmcauley** [tsujan/BreezeEnhanced#31]
The BreezeEnhanced config is stored in ~/.config/breezerc . This file is meant for Breeze's settings!! You can give your settings a unique name instead by editing breezesettingsdata.kcfg and changing <kcfgfile name="breezerc"/> to something unique!

**Comment by tsujan** [comment]
Unlike my other repositories, BreezeEnhanced isn't really my program but just a collection of changes I made to the code of Breeze title-bar. So, I left the config file as it was.

Since changing the config file would break backward compatibility, I'm not sure it's a good idea.

**Comment by paulmcauley** [comment]
I think the fact you are corrupting another co-existing plugin's (upstream Breeze's) settings should be a bigger priority than the minor hassle of a user having to reconfigure his settings!!!

**Comment by tsujan** [comment]
"Corrupted" has a real meaning in computing. No config file is corrupted. Most keys are shared and Breeze doesn't read the extra keys.
