### ISSUE TITLE
Make titlebar metrics configurable

### ISSUE THREAD

**Issue by probonopd** [tsujan/BreezeEnhanced#32]
A common complaint about the upstream Breeze theme is that the title bars are too big and cannot be configured in a fine-grained way. I understand that BreezeEnhanced was made to make it more configurable, and I think it would be nice if titlebar metrics could also be made configurable via `breezerc`. 

For example, I would like to achieve this result:

![image](https://user-images.githubusercontent.com/2480569/115433891-57b74a00-a208-11eb-9db8-484d49dea767.png)

Especially, I would like to be able to set:
* The title bar radius in pixels
* The height of the title bar in pixels (e.g., 22 pixels, independent of font size)
* Padding in the title bar in pixels (not in "units of small spacing", whatever that is supposed to be)

See `breezedecoration.cpp` and `breeze.h` in

https://github.com/helloSystem/BreezeEnhanced/commit/27a05ac4fb3b0e397acb468ae929b7167fe18791

for the type of changes I would like to see made configurable, so that one doesn't have to fork BreezeEnhanced just to make these kinds of configuration changes.

**Comment by tsujan** [comment]
Your feature request is quite valid.

But, as I said in https://github.com/tsujan/BreezeEnhanced/issues/31#issuecomment-822788786, I don't consider BreezeEnhanced as my *program*. It's rather the result of applying some patches of mine to Breeze, for using it with Kvantum. To me, it's 99% Breeze. What I do here is only updating it whenever needed. Having a limited amount of free time, which I spend on my own projects, I couldn't do that if it gets too different from Breeze.

So, I think the only way is forking. Sorry!

**Comment by probonopd** [comment]
Had you ever tried to get your improvements into upstream Breeze?

**Comment by probonopd** [comment]
Would you happen to know how to disable the right-click menu that appears when one right-clicks on the  window title? It contains KDE Plasma specific menu entries that do not even work when the full KDE Plasma desktop is not installed.

**Comment by probonopd** [comment]
![image](https://user-images.githubusercontent.com/2480569/115453687-2f3b4a00-a220-11eb-8cd3-fa695798f0b4.png)

**Comment by tsujan** [comment]
Here, the same menu appears on left clicking the window icon, not right clicking the title-bar:

![menu](https://user-images.githubusercontent.com/981076/115454223-c6f76300-a235-11eb-90d4-a826da34e095.png)

I don't know where its source is. I think it's quite useful.
