### ISSUE TITLE
Building on focal/bionic fails due to not finding QColor

### ISSUE THREAD

**Issue by nullket** [tsujan/BreezeEnhanced#33]
Hey,

great looking enhancement to the regular option! 

I am trying to build it form source under Kubuntu 20.04.

make fails with `fatal error: QColor: No such file or directory`
<details>
  <summary>Click to expand full make log</summary>
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.68.0") 
-- Found KF5GuiAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (found version "5.68.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.68.0") 
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.68.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.68.0") 
-- Found KF5: success (found version "5.68.0") found components: CoreAddons GuiAddons ConfigWidgets WindowSystem I18n 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.14") 
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.14") found components: XCB 
-- Warning: Property URL already set to "https://xcb.freedesktop.org/", overriding it with "https://xcb.freedesktop.org"
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:95 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhanced" links to target "Qt::Core" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:95 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhanced" links to target "Qt::Gui" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:95 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhanced" links to target "Qt::DBus" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:95 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhanced" links to target "Qt::Core" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:95 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhanced" links to target "Qt::Gui" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:95 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhanced" links to target "Qt::X11Extras" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libbreezecommon/CMakeLists.txt:10 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhancedcommon5" links to target "Qt::Core" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libbreezecommon/CMakeLists.txt:10 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "breezeenhancedcommon5" links to target "Qt::Gui" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/username/Dokumente/Look/BreezeEnhanced/build
username@n1053:~/Dokumente/Look/BreezeEnhanced/build$ make
Scanning dependencies of target breezeenhancedcommon5_autogen
[  4%] Automatic MOC for target breezeenhancedcommon5
[  4%] Built target breezeenhancedcommon5_autogen
Scanning dependencies of target breezeenhancedcommon5
[  8%] Building CXX object libbreezecommon/CMakeFiles/breezeenhancedcommon5.dir/breezeenhancedcommon5_autogen/mocs_compilation.cpp.o
[ 12%] Building CXX object libbreezecommon/CMakeFiles/breezeenhancedcommon5.dir/breezeboxshadowrenderer.cpp.o
In file included from /home/username/Dokumente/Look/BreezeEnhanced/libbreezecommon/breezeboxshadowrenderer.cpp:22:
/home/username/Dokumente/Look/BreezeEnhanced/libbreezecommon/breezeboxshadowrenderer.h:25:10: fatal error: QColor: No such file or directory
   25 | #include <QColor>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [libbreezecommon/CMakeFiles/breezeenhancedcommon5.dir/build.make:76: libbreezecommon/CMakeFiles/breezeenhancedcommon5.dir/breezeboxshadowrenderer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:461: libbreezecommon/CMakeFiles/breezeenhancedcommon5.dir/all] Error 2
make: *** [Makefile:130: all] Error 2  
</details>

I am able to locate QColor:
```bash
locate QColor 
/usr/include/x86_64-linux-gnu/qt5/QtGui/QColor
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QColorDialog
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QColormap
```

For the same reason some of the ppa builds seem to fail: https://launchpadlibrarian.net/550784023/buildlog_ubuntu-bionic-amd64.breezeenhanced_0.V5.21-0~202107300147~rev43~pkg1~ubuntu18.04.1_BUILDING.txt.gz

**Comment by tsujan** [comment]
> I am trying to build it form source under Kubuntu 20.04.

You need to find the version of KWin in Kubuntu 20.04 and choose a compatible version of BreezeEnhanced from https://github.com/tsujan/BreezeEnhanced/releases. The git source is for the latest KWin and Qt5.
