### ISSUE TITLE
Not Working after compiling; Cannot load library

### ISSUE THREAD

**Issue by aragubas** [tsujan/BreezeEnhanced#34]
# Not working after compiling
I just compiled BreezeEnchanced, no build errors; I logged in and out and the theme didn't appered. I tried to open BreezeEnhanced on the menu and this window appers:

![image](https://user-images.githubusercontent.com/47148297/135685054-46c1cf90-03e9-49e5-8641-1806f980b505.png)

My system is Fedora 34

# Some output files:
[CMakeOutput.log](https://github.com/tsujan/BreezeEnhanced/files/7270105/CMakeOutput.log)
34

**Comment by tsujan** [comment]
> I just compiled BreezeEnchanced

Against which version of KWin and which version of Qt?

**Comment by aragubas** [comment]
> > I just compiled BreezeEnchanced
> 
> Against which version of KWin and which version of Qt?

kwin version is 5.22.4
qt version is 5.15.2

btw, i copied the file `build/libbreezecommon/libbreezeenhancedcommon5.so.0.1` to /usr/lib64/usr/lib64/libbreezeenhancedcommon5.so.0 and its working now

**Comment by tsujan** [comment]
OK, the versions are good.

Fedora uses `lib64`, not `lib`. So, the generic cmake command in "README.md" should be modified for it.

I'll add a warning to "README.md" like this:

"`KDE_INSTALL_LIBDIR` may be different in some distros. Please consult your distro doc to find the correct directory or, preferably, do the compilation in the way that is done in your distro, by making an installable package."

Thanks for the report!

**Comment by tsujan** [comment]
BTW, with `lib`, the installed files are only these:

```
/usr/lib/libbreezeenhancedcommon5.so.0.1
/usr/lib/libbreezeenhancedcommon5.so.0 (symlink to libbreezeenhancedcommon5.so.0.1)
/usr/lib/qt/plugins/org.kde.kdecoration2/breezeenhanced.so
/usr/share/kservices5/breezeenhancedconfig.desktop
```

If you want to recompile it correctly, first remove them (after switching back to Breeze).

In all distros, making installable packages is highly preferable (rpm for Fedora) to a direct installation from the source because, only with the former, the package manager could control everything.
