### ISSUE TITLE
Create a tag for the current release

### ISSUE THREAD

**Issue by InternetUnexplorer** [tsujan/BreezeEnhanced#39]
Hi there, I noticed that there are only tags for previous versions (e.g. when the latest version was 5.23 the latest tag was 5.22, and now the latest version is 5.24 and the latest tag is 5.23). Would it be possible to tag the latest release as well? Thanks a bunch! :)

**Comment by tsujan** [comment]
Hi,

BreezeEnhanced is actually nothing but a set of patches that I've made and applied to Breeze. More than 90% of its code is that of Breeze. To keep it up-to-date, I follow the development of Breeze and make the same changes to BreezeEnhanced (perhaps, except for a few). Therefore, it can be released only after Breeze bumps its version.

If you have a distro with the latest stable version of KWin (like Arch, Manjaro, OpenSUSE Tumbleweed,..), you need the git master of BreezeEnhanced. The released versions may only be useful for users of distros (like Ubuuntu, Fedora,...) with older versions of KWin.

Make sure that the version number inside the file NEWS matches the major and minor versions of your installed KWin (the patch version of KWin isn't so important).

**Comment by InternetUnexplorer** [comment]
That makes sense, thanks for explaining :)
