### ISSUE TITLE
titlebar changes with kde 5.25.0 (not blurred anymore)

### ISSUE THREAD

**Issue by slynobody** [tsujan/BreezeEnhanced#40]
You should take a look into what changed with 5.25.0. 
windows titlebars after applying the theme do *not* look the way like before if you change opacity, it completely *lost blur effect* (tried recompiling it with updated decorations-dev, same problem).

**Comment by tsujan** [comment]
> You should take a look into what changed with 5.25.0.

I will, when it comes here. The current git master is for 5.24 (→ https://github.com/tsujan/BreezeEnhanced/blob/master/NEWS).

**Comment by tsujan** [comment]
Breeze 5.25.0 hasn't come here yet, but I saw its source: other than a few Qt6 checks, nothing has changed. The apparent changes are all trivial and just about the code style -- spaces, new lines, parentheses, etc.

However, your answer is here: https://psifidotos.blogspot.com/2022/03/kornersfix.html

The bad news is that KDE disabled decoration blurring in 5.25. That's the cause of what you see.

The good news is that I might be able to restore blurring in a better form, by adding codes to BreezeEnhanced. That will take time. Until then, if blurring is very important to you, you might want to check Aurorae.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/BreezeEnhanced/commit/e9235c91724913a2cf3153d7e47b963917e51677.
