### ISSUE TITLE
5.25 / blur / update to sierrabreezeenhanced changes?

### ISSUE THREAD

**Issue by usablelinux** [tsujan/BreezeEnhanced#41]
Hi,

could you please update to let this work with 5.25, f.e. by including the latest commit from [sierrabreezeenhanced](https://github.com/kupiqu/SierraBreezeEnhanced/commit/57ca3abb40703c03844a8e8c398505b2c0d1c8d6)?
or are this commits already useable in patch-form for this repo too?

sincerely

**Comment by tsujan** [comment]
Please see https://github.com/tsujan/BreezeEnhanced/issues/37#issuecomment-1160499907 and the comment after it.

In short, I made a patch 2 months ago, but I can't do anything until Manjaro Testing changes its weird behavior regarding Plasma 5.25.

If they continue this behavior, I might migrate to Arch. Please be patient.

**Comment by tsujan** [comment]
5.25 came here at last and I added the code I'd prepared (https://github.com/tsujan/BreezeEnhanced/commit/e9235c91724913a2cf3153d7e47b963917e51677). You could upgrade.
