### ISSUE TITLE
setBlurRegion not declared

### ISSUE THREAD

**Issue by minorsecond** [tsujan/BreezeEnhanced#42]
What is `setBlurRegion()` at line 453 in `breezedecoration.cpp` referring to? It seems like that function isn't declared anywhere. I'm unable to compile the project. I did a search across the files but couldn't find the declaration.

**Comment by tsujan** [comment]
I guess you found the answer and closed the report. But, for the record, it uses the new blurring functionality of KWin 5.25, which makes it possible to avoid blur glitches at corners.

**Comment by minorsecond** [comment]
Yes, I realized shortly after creating this that I missed the part of the
README that mentioned the required version. I'm at 5.24 so looks like I'll
have to wait to use the theme. Thanks!

**Comment by tsujan** [comment]
> I'm at 5.24

I always make a simple release out of the previous version before working on the new one. 5.24 is here: https://github.com/tsujan/BreezeEnhanced/releases/tag/V5.24

You could find all releases here: https://github.com/tsujan/BreezeEnhanced/releases

**Comment by minorsecond** [comment]
Awesome, thanks!
