### ISSUE TITLE
No support for KDE 6

### ISSUE THREAD

**Issue by arithefirst** [tsujan/BreezeEnhanced#46]
When attempting to install Breeze Enhcnced on KDE 6, I get the following error:
```
CMake Error: The INTERFACE_QT_MAJOR_VERSION property of "Qt6::Gui" does
not agree with the value of QT_MAJOR_VERSION already determined
for "breezeenhanced"```

**Comment by tsujan** [comment]
Not reproducible. The latest git BreezeEnhanced needs Qt ≥ 6.6.0.

Also, if you use a distro that separates "dev" packages (like Debian, Fedora,...), make sure you've installed them correctly.
