### ISSUE TITLE
Update breezebutton's public constructor

### ISSUE THREAD

**Issue by trmdi** [tsujan/BreezeEnhanced#7]
Hi,
From this: https://phabricator.kde.org/D16596
Could you please update breezebutton.cpp ?

**Comment by tsujan** [comment]
I should study the patch first; will do it soon -- maybe tomorrow. Thanks for telling me about it :)

**Comment by tsujan** [comment]
Found time and did it in https://github.com/tsujan/BreezeEnhanced/commit/159012b1afa32515b79ed419b9cd976e9e23303e

I don't use the property this patch is supposed to fix but it exactly reflects the upstream change. I hope it'll be useful to you.

Every time a new release of Breeze is published, I check its differences from the last one and make similar changes to BreezeEnhanced if relevant. However, if you want to have a feature sooner, please keep telling me about changes!

**Comment by trmdi** [comment]
Thank you @tsujan !

**Comment by tsujan** [comment]
You're welcome. Did it help?
