### ISSUE TITLE
Window titlebar color

### ISSUE THREAD

**Issue by lyndhurst** [tsujan/BreezeEnhanced#8]
Hi, 
I just discovered the kvMojave theme, which is great, so I tried this window border theme.
I am on kubuntu 18.04.1 fesh install, I have kvantum 0.10.9 installed.

I built BreezeEnhanced from source, everything went fine. The theme appears, the configuration menu is available, and working. BTW, the whole thing looks amazing !!!

My only problem is that the BreezeEnhanced border theme installed has blue titlebar matching the original Breeze theme. I was expecting a Grey/Dark title bar matching the screenshots.

Am I missing something?

**Comment by tsujan** [comment]
Breeze and BreezeEnhanced take their colors from the KDE color scheme. For every Kvantum theme, a KDE color scheme is also installed. So, you have to select KvMojave in System Settings → Colors.

In future, I might add an overriding option for the title-bar color.

**Comment by lyndhurst** [comment]
Thank you very much for your quick help ;)
It worked perfectly, and, this kvantum theme and window border are really impressive.
The level of details and readability are the best I have seen for a dark theme !

**Comment by tsujan** [comment]
You're welcome.

Kvantum themes enforce their colors but some KDE components get their colors directly from the KDE color scheme (as is mentioned in Kvantum Manager). So, under KDE, the color scheme should be applied too whenever the Kvantum theme is changed.
