### ISSUE TITLE
Feature request Yakuake skin for KDE

### ISSUE THREAD

**Issue by lyndhurst** [tsujan/BreezeEnhanced#9]
Hi,
This is not an issue, but I have been using kvMojave, and BreezeEnhanced, the combination is really great.
The only thing missing is a matching skin for Yakuake, should I ask for it somewhere else or am I in the right place ?
Thanks for the great themes anyway.

**Comment by tsujan** [comment]
BreezeEnhanced isn't and won't be related to Yakuake or any other terminal emulator but Konsole and QTerminal (and, perhaps, Yakuake) can be made like this with it:

![qterminal](https://user-images.githubusercontent.com/981076/48025195-f6927d80-e157-11e8-8b25-099f20d3f6cf.png)

**Comment by lyndhurst** [comment]
I understand that theming of the terminal itself whatever the app I am using is not linked to BreezeEnhanced.
.
I was referring to Yakuake, because it integrates well with KDE, and "skins" are just a bottom window border with window buttons, tabs, and a menu button. Not the output screen of the terminal.

I cannot get a screenshot right now, but this Yakuake bottom window border is not inherited from KDE systemsettings, and nothing in the kde store matches breezemite borders, or BreezeEnhanced themes and buttons.

That is why I beliebe it would be a great addition for users who like drop down terminal application and use BreezeEnhanced.
Thank you anyway :)

**Comment by tsujan** [comment]
> but this Yakuake bottom window border is not inherited from KDE systemsettings

BreezeEnhanced is essentially the Breeze title-bar plus some enhancements. Every thing that uses the Breeze title-bar will use BreezeEnhanced too, and conversely.

Maybe what you see is a menu-bar or tool-bar, not a title-bar. In that case, neither Breeze nor BreezeEnhanced cannot affect it.

**Comment by tsujan** [comment]
> ... just a bottom window border with window buttons, tabs, and a menu button

Oh, that should be Yakuake's tool-bar.

**Comment by lyndhurst** [comment]
Yes, in the Yakuake menu they call it a "Skin" I think. Maybe it is better with a picture.

I was thinking of "cooking" something up based on free skins, and 'breesemite dark optimized" window border svg files. But I have litterally no skills with Inkscape, that is why I tried here :)

![yakua-brzen](https://user-images.githubusercontent.com/30077629/48027344-d3ac9d00-e148-11e8-97ad-a9446ca7bee7.png)

**Comment by tsujan** [comment]
I've never used Yakuake. If it's a skin, it's fully controlled by Yakuake.

Anyhow, BreezeEnhanced only controls the title-bar. Kvantum controls how all widgets look, except for those that are drawn in apps' codes (like this case, perhaps) and QML apps (which always have a terrible look).
